config/routes.rb
Rails.application.routes.draw do

  root "mains#index"
  resources :users do
    resources :bookings do
      put 'confirm'
      put 'cancel'
    end 
  end
  
  resources :categories
  resources :events
  resources :roles
  resources :cities
  resources :locations
  resources :notifications
  get "/bookings", to: "bookings#index", as: "bookings"
  get "/bookings/show", to: "bookings#show", as: "bookings_show"
  get "/events/populate_location", to: "events#populate_location"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :event
  belongs_to :user
  has_many :notifications, as: :notifiable, dependent: :destroy
  enum status: { Failed: 0, Success: 1, Pending: 2} 

  after_create :create_notification
  private
  def create_notification
    self.notifications.create(message: "Booking for #{self.event.name} created")
  end
end
#you can set default value for status as pending
#also you can change the status of the boooking usin the key value for eg booking.confirmed!, or booking.pending! or u can check using booking.confirmed?
#event.bookings.sum(:capactiy) : for capacity in the bookings
#location.capacity - event.bookings.sum(:capactiy)

app/models/category.rb
class Category < ApplicationRecord
  has_many :events
end

app/models/city.rb
class City < ApplicationRecord
  has_many :locations
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :category
  belongs_to :location
  has_many :bookings
  has_many :users, through: :bookings
  has_many :notifications, as: :notifiable, dependent: :destroy

  after_create :create_notifications
  private
  def create_notifications
    self.notifications.create(message: "#{self.name} event created ")
  end
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :city
  has_many :events
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :notifiable, polymorphic: true

  def display_name
    notifiable_type.eql?('Event') ? notifiable.name : notifiable.event.name
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :events, through: :bookings
  has_and_belongs_to_many :roles
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @booking = Booking.all
  end

  def new
    @user = User.find(params[:user_id])
    @booking = Booking.new
  end

  def create
    @user = User.find(params[:user_id])
    @booking = @user.bookings.new(booking_params)

    if @booking.save
      redirect_to user_bookings_path
    else
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:format])
  end

  def confirm
    @booking = Booking.find_by(id: params[:booking_id])
    @booking.Success!
    redirect_to bookings_path, status: 303
  end

  def cancel
    @booking = Booking.find_by(id: params[:booking_id])
    @booking.Failed!
    redirect_to bookings_path, status: 303
  end

  def update
    @booking = Booking.find(params[:format])
    if @booking.update([:status])
      redirect_to user_bookings_path
    else
      render :show, status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:user_id, :event_id, :capacity, :status, :reason)
  end
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  def index
    @role = Role.all
  end

  def new
    @role = Role.new
  end
  def create
    @role = Role.new(role_params)

    if @role.save
      redirect_to roles_path
    else
      render :new
    end
  end
  private
  def role_params 
    params.require(:role).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.roles << Role.find_by(id: params[:user][:role_ids])
    if @user.save
      redirect_to users_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :phone, :email, :role_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/index.html.erb
<table>
<thead>
<th>User</th>
<th>Event</th>
<th>Status</th>
<th>View</th>
</thead>
<tbody>
<% @booking.each do |b| %>
<tr>
<td><%= b.user.name %></td>
<td><%= b.event.name %></td>
<td><%= b.status %></td>
<td><%= link_to "View", bookings_show_path(b) %></td>
</tr>
<% end %>
</tbody>
</table>

app/views/bookings/new.html.erb
<h1>Make a new Booking!</h1>

<%= form_with model: [ @user, @user.bookings.build ] do |f| %>

<div>
<%= f.label :event_id %>
<%= collection_select(:booking, :event_id, Event.all, :id, :name, {:prompt => "Select an event"})%></div><br>

<div>
<%= f.label :capacity %>
<%= f.text_field :capacity %></div><br>

<div>
<%= f.submit %>
</div>
<% end %>

app/views/bookings/show.html.erb
<fieldset>
<h2>Event</h2>
<table>
<thead>
<th>Name</th>
<th>Start time</th>
<th>End time</th>
<th>Location</th>
<th>City</th>
<th>Category</th>
</thead>
<tbody>
<tr>
<td><%= @booking.event.name %></td>
<td><%= @booking.event.start_time %></td>
<td><%= @booking.event.end_time %></td>
<td><%= @booking.event.location.name %></td>
<td><%= @booking.event.location.city.name %></td>
<td><%= @booking.event.category.name %></td>
</tr>
</tbody>
</table>
</fieldset><br><br>
<fieldset>
<h2>User</h2>
<table>
<thead>
<th>Name</th>
<th>Phone Number</th>
<th>Email</th>
</thead>
<tbody>
<tr>
<td><%= @booking.user.name %></td>
<td><%= @booking.user.phone %></td>
<td><%= @booking.user.email %></td>
</tr>
</tbody>
</table>
</fieldset>
<h3>Change the status!</h3>
<%= link_to 'Confirm', user_booking_confirm_path(user_id: @booking.user.id, booking_id: @booking.id), data: { "turbo-method": :put } %>
<%= link_to 'Cancel', user_booking_cancel_path(user_id: @booking.user.id, booking_id: @booking.id), data: { "turbo-method": :put } %>