config/routes.rb
Rails.application.routes.draw do

  root "mains#index"
  resources :users do
    resources :bookings do
      put 'confirm'
      put 'cancel'
    end 
  end
  
  resources :categories
  resources :events
  resources :roles
  resources :cities
  resources :locations
  resources :notifications
  get "/bookings", to: "bookings#index", as: "bookings"
  get "/bookings/show", to: "bookings#show", as: "bookings_show"
  get "/events/populate_location", to: "events#populate_location"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :event
  belongs_to :user
  has_many :notifications, as: :notifiable, dependent: :destroy
  enum status: { Failed: 0, Success: 1, Pending: 2} 

  after_create :create_notification
  private
  def create_notification
    self.notifications.create(message: "Booking for #{self.event.name} created")
  end
end
#you can set default value for status as pending
#also you can change the status of the boooking usin the key value for eg booking.confirmed!, or booking.pending! or u can check using booking.confirmed?
#event.bookings.sum(:capactiy) : for capacity in the bookings
#location.capacity - event.bookings.sum(:capactiy)

app/models/category.rb
class Category < ApplicationRecord
  has_many :events
end

app/models/city.rb
class City < ApplicationRecord
  has_many :locations
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :category
  belongs_to :location
  has_many :bookings
  has_many :users, through: :bookings
  has_many :notifications, as: :notifiable, dependent: :destroy

  after_create :create_notifications
  private
  def create_notifications
    self.notifications.create(message: "#{self.name} event created ")
  end
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :city
  has_many :events
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :notifiable, polymorphic: true

  def display_name
    notifiable_type.eql?('Event') ? notifiable.name : notifiable.event.name
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :events, through: :bookings
  has_and_belongs_to_many :roles
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @event = Event.all
  end

  def new
    @event = Event.new

    if request.xhr?
      respond_to do |format|
        format.json {
          render json: { locations: Location.where("city_id = ?", params[:city_id]) }
        }
      end
    end
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :start_time, :end_time, :city_id, :category_id, :location_id)
  end
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  def index
    @role = Role.all
  end

  def new
    @role = Role.new
  end
  def create
    @role = Role.new(role_params)

    if @role.save
      redirect_to roles_path
    else
      render :new
    end
  end
  private
  def role_params 
    params.require(:role).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.roles << Role.find_by(id: params[:user][:role_ids])
    if @user.save
      redirect_to users_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :phone, :email, :role_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>Events</h1>
<table>
<thead>
<th>Name</th>
<th>Start time</th>
<th>End time</th>
<th>Location</th>
<th>City</th>
<th>Category</th>
<th>Seats Left</th>
</thead>
<tbody>
<% @event.each do |e| %>
<tr>
<td><%= e.name %></td>
<td><%= e.start_time %></td>
<td><%= e.end_time %></td>
<td><%= e.location.name %></td>
<td><%= e.location.city.name %></td>
<td><%= e.category.name %></td>
<td><%= e.location.capacity - e.bookings.sum(:capacity)%>
</tr>
<% end %>
</tbody>
</table>

<%= link_to "Add New Event",  new_event_path %>

app/views/events/new.html.erb
<h1>Add New Event</h1>
<%= form_with model: @event do |form| %>
<div>
<%= form.label :name %>
<%= form.text_field :name%>
</div><br>
<div>
<%= form.label :start_time %>
<%= form.datetime_field :start_time%>
</div><br>
<div>
<%= form.label :end_time %>
<%= form.datetime_field :end_time%>
</div><br>
<div>
<%= form.label 'City' %>
<%= select_tag "cities", options_from_collection_for_select(City.all, "id", "name"), {:prompt => "Select City"} %>
</div><br>
<div>
<%= form.label :location_id %>
<%= collection_select(:event, :location_id, Location.all, :id, :name, {:prompt => "Select Location"}, {:disabled => true}) %>
</div><br>
<div>
<%= form.label :category_id %>
<%= collection_select(:event, :category_id, Category.all, :id, :name, {:prompt => "Select Category--"})%>
</div><br>
<div>
<%= form.submit %>
</div><br>
<% end %>