config/routes.rb
Rails.application.routes.draw do

  root "mains#index"
  resources :users do
    resources :bookings do
      put 'confirm'
      put 'cancel'
    end 
  end
  
  resources :categories
  resources :events
  resources :roles
  resources :cities
  resources :locations
  resources :notifications
  get "/bookings", to: "bookings#index", as: "bookings"
  get "/bookings/show", to: "bookings#show", as: "bookings_show"
  get "/events/populate_location", to: "events#populate_location"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :event
  belongs_to :user
  has_many :notifications, as: :notifiable, dependent: :destroy
  enum status: { Failed: 0, Success: 1, Pending: 2} 

  after_create :create_notification
  private
  def create_notification
    self.notifications.create(message: "Booking for #{self.event.name} created")
  end
end
#you can set default value for status as pending
#also you can change the status of the boooking usin the key value for eg booking.confirmed!, or booking.pending! or u can check using booking.confirmed?
#event.bookings.sum(:capactiy) : for capacity in the bookings
#location.capacity - event.bookings.sum(:capactiy)

app/models/category.rb
class Category < ApplicationRecord
  has_many :events
end

app/models/city.rb
class City < ApplicationRecord
  has_many :locations
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :category
  belongs_to :location
  has_many :bookings
  has_many :users, through: :bookings
  has_many :notifications, as: :notifiable, dependent: :destroy

  after_create :create_notifications
  private
  def create_notifications
    self.notifications.create(message: "#{self.name} event created ")
  end
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :city
  has_many :events
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :notifiable, polymorphic: true

  def display_name
    notifiable_type.eql?('Event') ? notifiable.name : notifiable.event.name
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :events, through: :bookings
  has_and_belongs_to_many :roles
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @city = City.all
  end

  def new
    @city = City.new
  end

  def create
    @city = City.new(city_params)

    if @city.save
      redirect_to cities_path
    else
      render :new
    end
  end
  private
  def city_params 
    params.require(:city).permit(:name)
  end
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  def index
    @role = Role.all
  end

  def new
    @role = Role.new
  end
  def create
    @role = Role.new(role_params)

    if @role.save
      redirect_to roles_path
    else
      render :new
    end
  end
  private
  def role_params 
    params.require(:role).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.roles << Role.find_by(id: params[:user][:role_ids])
    if @user.save
      redirect_to users_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :phone, :email, :role_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/index.html.erb
<h1>Cities</h1>
<table>
<thead>
<th>Name</th>
</thead>
<tbody>
<% @city.each do |city| %>
<tr>
<td><%= city.name %></td>
</tr>
<% end %>
</tbody>
</table>

<%= link_to "Add New City",  new_city_path %>

app/views/cities/new.html.erb
<h1>New City</h1>
<%= form_with model: @city do |form| %>
<div>
  <%= form.label :name %>
  <%= form.text_field :name %></div><br>
<div>
<div>
  <%= form.submit %>
</div>

<% end %>

app/views/roles/index.html.erb
<h1>Roles</h1>
<table>
<thead>
<th>Name</th>
</thead>
<tbody>
<% @role.each do |r| %>
<tr>
<td><%= r.name %></td>
</tr>
<% end %>
</tbody>
</table>

<%= link_to "Add New Role",  new_role_path %>

app/views/roles/new.html.erb
<h1>New Roles</h1>
<%= form_with model: @role do |form| %>
<div>
  <%= form.label :name %>
  <%= form.text_field :name %></div><br>
<div>
<div>
  <%= form.submit %>
</div>

<% end %>

app/views/users/index.html.erb
<table>
<thead>
<th>Name</th>
<th>Phone</th>
<th>Email</th>
<th>Role</th>
<th>Book!</th>
</thead>
<tbody>
<% @user.each do |user| %>
<tr>
<td><%= user.name %></td>
<td><%= user.phone %></td>
<td><%= user.email %></td>
<td><%= user.roles.first.name%></td>
<td><%= link_to "Book", new_user_booking_path(user) %></td>
</tr>
<% end %>
</tbody>
</table>

<%= link_to "Add New User",  new_user_path %>

app/views/users/new.html.erb
<h1>Add New User</h1>

<%= form_with model: @user do |form| %>
<div>
  <%= form.label :name %>
  <%= form.text_field :name %></div><br>
<div>
  <%= form.label :phone %>
  <%= form.text_field :phone %></div><br>
<div>
  <%= form.label :email %>
  <%= form.text_field :email %></div><br>
<div>
  <%= form.label :role_id %>
  <%= collection_select(:user, :role_ids, Role.all, :id, :name, {:prompt => "Select Role"})%></div><br>
<div>
  <%= form.submit %>
</div>

<% end %>